Update tutorials on how to import CSV files
neo4j/docs-getting-started pull request #166
Opened 2022-12-21 12:22 UTC by NataliaIvakina

At the moment, we have more than one tutorial on how to import CSV files into Neo4j in the _Getting Started Guide_. They all have to be updated according to the v5. Also I replaced images.

2023-01-02 10:34 UTC, gem-neo4j requested changes
Looks good overall! Just a few comments about the Cypher shell that should be clarified :)

2023-01-02 10:34 UTC, gem-neo4j commented on modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
> +} IN TRANSACTIONS OF 500 ROWS
Is there a reason you started accessing the data as a list (row[0]) instead of using the headers? The purpose or using WITH HEADERS allows one to access the fields using the column names. I think it would look better like:
```suggestion
CALL {
 WITH row
 MATCH (p:Product {productId: toInteger(row.productID})
 MATCH (o:Order {orderId: toInteger(row.orderID})
 MERGE (o)-[rel:CONTAINS {quantityOrdered: toInteger(row.quantity}]->(p)
 RETURN count(rel)
} IN TRANSACTIONS OF 500 ROWS
```

2023-01-02 10:34 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +} IN TRANSACTIONS OF 2 ROWS
This is also using `WITH HEADERS`:

```suggestion
LOAD CSV WITH HEADERS FROM 'file:///roles.csv' AS csvLine
CALL {
 WITH csvLine
 MATCH (person:Person {id: toInteger(csvLine.personId)}), (movie:Movie {id: toInteger(csvLine.movieId)})
CREATE (person)-[:ACTED_IN {role: csvLine.role}]->(movie)
} IN TRANSACTIONS OF 2 ROWS
```

2023-01-02 10:34 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine MATCH (person:Person {id:toInteger(csvLine.personId)}), (movie:Movie {id:toInteger(csvLine.movieId)}) CREA
This doesn't have any reference to CALL IN TRANSACTIONS? That should be added right?

2023-01-02 10:34 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +But Cypher Shell supports _explicit_ transactions.
Cypher Shell support both explicit and implicit transactions, the difference is that in Browser one needs to explicitly say `:auto` whereas in Cypher Shell it will work straight away.

> RETURN 1; // Run in implicit transaction

> :begin
> RETURN 1; // Run in explicit transaction
> :commit

2023-01-04 07:58 UTC, NataliaIvakina commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine MATCH (person:Person {id:toInteger(csvLine.personId)}), (movie:Movie {id:toInteger(csvLine.movieId)}) CREA
Yes, you're right. I'm not sure how to modify this statement because of the necessity to prepend `:auto` in the interactive Cypher Shell. In fact, it means we need to add two code examples: one for Cypher Shell itself and one for Cypher Shell in Browser (interactive one, as it's named in the docs).

`bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine
CALL {MATCH (person:Person {id: toInteger(csvLine.personId)}), (movie:Movie {id: toInteger(csvLine.movieId)})
CREATE (person)-[:ACTED_IN {role: csvLine.role}]->(movie)} IN TRANSACTIONS OF 500 ROWS'`

`:auto
neo4j# LOAD CSV WITH HEADERS FROM 'file:///roles.csv' AS csvLine
CALL 
{MATCH (person:Person {id: toInteger(csvLine.personId)}), (movie:Movie {id: toInteger(csvLine.movieId)})
CREATE (person)-[:ACTED_IN {role: csvLine.role}]->(movie)
} IN TRANSACTIONS OF 500 ROWS`

2023-01-04 14:25 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine MATCH (person:Person {id:toInteger(csvLine.personId)}), (movie:Movie {id:toInteger(csvLine.movieId)}) CREA
This specific one doesn't need :auto as it is for Cypher shell. The previous statement above would need it though

2023-01-05 10:39 UTC, NataliaIvakina commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +====
@gem-neo4j, I edited the admonition. Could you take a look, please? Is that correct now? I don't know why but in the Cypher docs there are no mentions that you need to prepend CALL {} with `:auto`.

2023-01-05 10:57 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +====
In the docs currently; https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/#subquery-call-in-transactions has a note saying it is only allowed in implicit transactions and then links to the docs about how to use implicit transactions :)

This admonition is correct, but perhaps linking here: https://neo4j.com/docs/cypher-manual/current/introduction/transactions/ would be good so it is easier to understand why

2023-01-05 14:29 UTC, gem-neo4j approved these changes
Just a few comments, otherwise looking good :)

2023-01-05 14:29 UTC, gem-neo4j commented on modules/ROOT/pages/cypher-intro/load-csv.adoc
> +bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine CALL {MATCH (person:Person {id: toInteger(csvLine.personId)}), (movie:Movie {id: toInteger(csvLine.movieId
The previous example does it in rows of 2:

```suggestion
bin/cypher-shell --database=neo4j 'LOAD CSV WITH HEADERS FROM "file:///roles.csv" AS csvLine CALL {MATCH (person:Person {id: toInteger(csvLine.personId)}), (movie:Movie {id: toInteger(csvLine.movieId)}) CREATE (person)-[:ACTED_IN {role: csvLine.role}]->(movie)} IN TRANSACTIONS OF 2 ROWS'
```

2023-01-05 14:51 UTC, NataliaIvakina commented on modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
>  .. Enter `bin/cypher-shell`.
Oh, yes. You're absolutely right. Thank you.  This somehow escaped my attention. Perhaps, I just remove these screenshots, if we want to update this tutorial quickly.

2023-01-05 15:03 UTC, merged