Rename drivers section
neo4j/docs-getting-started pull request #217
Opened 2023-03-01 14:39 UTC by NataliaIvakina

Rename the section on Neo4j drivers
Update the first page of the section

2023-03-02 09:29 UTC, NataliaIvakina commented on modules/ROOT/pages/languages-guides/index.adoc
> +If you are new to development, we recommend the https://www.jetbrains.com/products.html[Jetbrains IDE^] for a good developer experience which also comes with a link:https://neo4j.com/blog/jetbrains-i
Should we recommend any platforms outside Neo4j? The blog they link to is a community blog, and the mentioned plugin was updated in 2020 last time and it's a community product, not officially supported (as I understand). 
It looks like better to remove this paragraph.

2023-03-02 14:35 UTC, NataliaIvakina commented on modules/ROOT/pages/languages-guides/index.adoc
> += Connecting to Neo4j
Honestly, I'm not totally happy with this title since the next section is named "Neo4j Connectors". 
Other options:
- Building/creating your application
- Using Neo4j from other programming languages
- Integrating Neo4j with your working environment - as a title for restructured drivers and connectors. In future, we can add GraphQL to this list

2023-03-02 16:25 UTC, davidoliverSP2 requested changes
Thanks @NataliaIvakina - some things to consider. Happy to discuss this strategy further if helpful 👍

2023-03-02 16:25 UTC, davidoliverSP2 commented on modules/ROOT/pages/languages-guides/index.adoc
> += Connecting to Neo4j
I see your concern here - however, I also think this is right title for this section 😄 

What I think the right thing to do here is some slight re-architecture, to move the connectors under this renamed section, and then remove the "Neo4j Connectors" section header. For example:

- Connecting to Neo4j
-- Using Neo4j with Python
-- Using Neo4j with Java
-- Using Neo4j with JavaScript
-- Using Neo4j with .NET
-- Using Neo4j with Go
-- Using Neo4j with Apache Spark
-- Using Neo4j with Apache Kafka
-- Using Neo4j with Business Intelligence
-- Using Neo4j with Community Drivers

There would then be scope for equivalent pages on using Neo4j with GraphQL, and using Neo4j with OGM/SDN

2023-03-02 16:25 UTC, davidoliverSP2 commented on modules/ROOT/pages/languages-guides/index.adoc
> +If you are new to development, we recommend the https://www.jetbrains.com/products.html[Jetbrains IDE^] for a good developer experience which also comes with a link:https://neo4j.com/blog/jetbrains-i
Yes, I don't think this is appropriate or easy for us to maintain. I think this sentence should be removed.

2023-03-03 11:39 UTC, NataliaIvakina commented on modules/ROOT/pages/languages-guides/index.adoc
> +If you are new to development, we recommend the https://www.jetbrains.com/products.html[Jetbrains IDE^] for a good developer experience which also comes with a link:https://neo4j.com/blog/jetbrains-i
Done!

2023-03-03 12:36 UTC, NataliaIvakina commented on modules/ROOT/pages/languages-guides/index.adoc
> += Connecting to Neo4j
I like your suggestions. Next PR will be dedicated to the restructuring of this section. I will add new subsection 'Using Neo4j with Community Drivers'.

2023-03-03 13:11 UTC, davidoliverSP2 approved these changes
Thanks @NataliaIvakina 

One small change to look at

2023-03-03 13:11 UTC, davidoliverSP2 commented on modules/ROOT/pages/languages-guides/index.adoc
> +If you want to access Neo4j programmatically, you can also use the HTTP API which allows you to:
```suggestion
If you want to access Neo4j programmatically, you can also use the HTTP API which enables you to:
```

2023-03-03 14:14 UTC, merged