Updated the graph database concept page.
neo4j/docs-getting-started pull request #35
Opened 2021-09-15 06:45 UTC by martin-neotech

Restructured content.
Added improved examples.
Added improved images.

2021-09-15 10:27 UTC, AlexicaWright reviewed
Great improvement @martin-neotech ! I left a bunch of comments :)

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +.Cypher.
Not sure if this is necessary here as this section describes the basic graph database concepts, not the Cypher language.

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +The simplest possible graph is a single node and no relationships.
```suggestion
The simplest possible graph is a single node with no relationships.
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +In the example graph the node labels are `Person`, `Actor`, and `Movie`, which is one possible way of describing the data.
```suggestion
In the example graph, the node labels are `Person`, `Actor`, and `Movie`, which is one way of describing the data.
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +<1> Note that you must create or reference two nodes to be able to create a relationship.
```suggestion
Note that you must create or reference two nodes to be able to create a relationship.
```
Alternatively, use a [NOTE] instead.

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
>  However, you only have to pay attention to the direction where it is useful.
```suggestion
However, the direction can be disregarded where it is not useful.
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
>  This means that there is no need to add duplicate relationships in the opposite direction unless it is needed in order to properly describe your use case.
```suggestion
This means that there is no need to add duplicate relationships in the opposite direction unless it is needed in order to properly describe the use case.
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
>  If we want to express that `Tom Hanks` `KNOWS` himself, that would be expressed as:
```suggestion
To express that `Tom Hanks` `KNOWS` himself would be expressed as:
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +The value part of the property can hold different data types such as `number`, `string`, and `boolean`.
```suggestion
The value part of the property can hold different data types, such as `number`, `string`, and `boolean`.
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
> +If we want to find out which movies Tom Hanks acted in according to our tiny example database, the traversal would start from the `Tom Hanks` node, follow any `ACTED_IN` relationships connected to th
```suggestion
To find out which movies Tom Hanks acted in according to the tiny example database, the traversal would start from the `Tom Hanks` node, follow any `ACTED_IN` relationships connected to the node, and end up with `Forrest Gump` as the result (see the dashed lines):
```

2021-09-15 10:27 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
>  It is recommended to follow the naming conventions described in the following table:
```suggestion
The following naming conventions are recommended:
```

2021-09-15 12:31 UTC, renetapopova requested changes
Thanks, @martin-neotech! Huge work! I added some suggestions.

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +* Nodes and relationships can contain *properties* (key-value pairs) that contain data.
```suggestion
* Nodes and relationships can have *properties* (key-value pairs) that contain data, which further describe them.
```

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +To create the example graph, use the Cypher clause `CREATE`.
I vote for Martin's sentence as it is in active voice instead of passive.

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +* A node can contain properties (key-value pairs) that contain data.
Those two are the same as the ones above.

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
>  Consider the graph below, consisting of a single node.
```suggestion
Consider the following graph, consisting of a single node.
```

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +.Cypher.
Agree with Jessica, the Example 2. Example graph suffices here. I think we don't need to introduce the CREATE clauses as we still haven't spoken about the different concepts in detail.

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
>  Labels are used to shape the domain by grouping nodes into sets where all nodes that have a certain label belongs to the same set.
```suggestion
Labels are used to shape the domain by grouping nodes into sets where all nodes with a certain label belong to the same set.
```

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
>  But assume that we want to express different dimensions of the data.
```suggestion
But assume that you want to express different dimensions of the data.
```

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
>  Below is an example showing the use of multiple labels:
I would remove that sentence.

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +* A relationship can contain properties (key-value pairs) that contain data.
```suggestion
* A relationship can contain properties (key-value pairs), which further describe the relationship.
```

2021-09-15 12:31 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
>  Node labels, relationship types and properties are case sensitive, meaning for example that the property `name` means something different than the property `Name`.
```suggestion
Node labels, relationship types, and properties are case sensitive, meaning, for example, that the property `name` is different from the property `Name`.
```

2021-09-15 12:40 UTC, AlexicaWright commented on modules/ROOT/pages/graphdb-concepts.adoc
>  But assume that we want to express different dimensions of the data.
I'd remove the subject altogether and say instead:
_More labels can be added to express different dimensions of the data._

2021-09-17 10:24 UTC, renetapopova reviewed
LGTM! Just 2 small suggestions.

2021-09-17 10:24 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +Labels are used to shape the domain by grouping (classify) nodes into sets where all nodes with a certain label belong to the same set.
```suggestion
Labels shape the domain by grouping (classifying) nodes into sets where all nodes with a certain label belong to the same set.
```

2021-09-17 10:24 UTC, renetapopova commented on modules/ROOT/pages/graphdb-concepts.adoc
> +* Can hold a homogeneous list (array) containing for example strings, numbers, or boolean values.
```suggestion
* Can hold a homogeneous list (array) containing, for example, strings, numbers, or boolean values.
```

2021-09-17 12:40 UTC, renetapopova approved these changes
Beautiful!

2021-09-17 13:07 UTC, AlexicaWright approved these changes
Wow! Great work @martin-neotech , thank you!

2021-09-17 15:23 UTC, MarkWoulfeNeo4j approved these changes
Just a couple of questions/potential suggestions but i'll leave it up to your judgement.

I do slightly worry that the inclusion of the arrows.app images might cause some confusion as these are mixed and matched with the original image design from dot but we can tackle this as a larger piece on graph diagrams in the docs in general.

2021-09-17 15:23 UTC, MarkWoulfeNeo4j commented on modules/ROOT/pages/graphdb-concepts.adoc
> +.Cypher.
As this is the first mention of cypher on the page, it might be nice to give it a brief introduction, even if that is just a hald sentence to introduce it as the 'query language cypher'.

2021-09-17 15:23 UTC, MarkWoulfeNeo4j commented on modules/ROOT/pages/graphdb-concepts.adoc
> +A relationship:
Not sure why type is bold but direction and properties are not.

2021-09-20 07:30 UTC, martin-neotech commented on modules/ROOT/pages/graphdb-concepts.adoc
> +.Cypher.
The first page does that.

2021-09-20 07:33 UTC, martin-neotech commented
> Just a couple of questions/potential suggestions but i'll leave it up to your judgement.
> 
> I do slightly worry that the inclusion of the arrows.app images might cause some confusion as these are mixed and matched with the original image design from dot but we can tackle this as a larger piece on graph diagrams in the docs in general.

This is an intermediate improvement for the images, we need to have a style guide for the visual aspects. There are more important things to improve first.

2021-09-20 07:34 UTC, martin-neotech commented on modules/ROOT/pages/graphdb-concepts.adoc
> +A relationship:
Because the relationship is all about (mostly) the type.

2021-09-20 07:35 UTC, merged