Add a link to the Cypher manual and fix links to the APOC docs
neo4j/docs-getting-started pull request #379
Opened 2024-03-07 15:08 UTC by NataliaIvakina

2024-03-07 15:11 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-379.surge.sh

Updated pages:
- [Graph model refactoring](https://neo4j-docs-getting-started-379.surge.sh/getting-started/data-modeling/graph-model-refactoring)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-07 15:15 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +After runnign the query, you see the following output:
```suggestion
After running the query, you see the following output:
```

2024-03-07 15:18 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-379.surge.sh

Updated pages:
- [Graph model refactoring](https://neo4j-docs-getting-started-379.surge.sh/getting-started/data-modeling/graph-model-refactoring)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-08 10:32 UTC, lidiazuin requested changes
thanks Natalia! I left some comments

2024-03-08 10:32 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +:description: This guide provides a worked example of changing a graph model. Upon finishing this guide, you should be able to evolve your graph model based on changing requirements.
What does "worked" mean here? As in "working"?

2024-03-08 10:32 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +It does this using the `apoc.refactor.normalizeAsBoolean` procedure, which itself takes in several parameters:
```suggestion
It does this by using the `apoc.refactor.normalizeAsBoolean` procedure, which itself takes in several parameters:
```

2024-03-08 10:46 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +:description: This guide provides a worked example of changing a graph model. Upon finishing this guide, you should be able to evolve your graph model based on changing requirements.
```suggestion
:description: This guide provides a working example of changing a graph model. Upon finishing this guide, you should be able to evolve your graph model based on changing requirements.
```

2024-03-08 10:46 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +:description: This guide provides a worked example of changing a graph model. Upon finishing this guide, you should be able to evolve your graph model based on changing requirements.
yeah, I think, you're right. They mean 'working'

2024-03-08 10:49 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +For more details about the `UNWIND` clause, go to the link:https://neo4j.com/docs/cypher-manual/current/clauses/unwind/[Cypher manual -> UNWIND].
I prefer to keep 'The Cypher manual' in the link description.

2024-03-08 10:55 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +You can evolve the model to create a `Flight` node from the properties stored on the `CONNECTED_TO` relationship.
I'm not sure that this is an improvement. I think, it's just a change to address your current needs

2024-03-08 11:01 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-379.surge.sh

Updated pages:
- [Graph model refactoring](https://neo4j-docs-getting-started-379.surge.sh/getting-started/data-modeling/graph-model-refactoring)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-08 11:09 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
>  Building on the Cypher basic concepts, this guide provides a worked example of changing a graph model.
```suggestion
Building on the Cypher basic concepts, this guide provides a working example of changing a graph model.
```

2024-03-08 11:59 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-379.surge.sh

Updated pages:
- [Graph model refactoring](https://neo4j-docs-getting-started-379.surge.sh/getting-started/data-modeling/graph-model-refactoring)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-08 13:26 UTC, NataliaIvakina commented on modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
> +You can then write the following query to find the airlines and number of flights involving each:
```suggestion
You can then write the following query to find the airlines and number of flights involving each airline:
```

2024-03-08 13:28 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-379.surge.sh

Updated pages:
- [Graph model refactoring](https://neo4j-docs-getting-started-379.surge.sh/getting-started/data-modeling/graph-model-refactoring)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 13:18 UTC, merged