Fix the OGM page
neo4j/docs-getting-started pull request #431
Opened 2024-11-15 14:36 UTC by NataliaIvakina

2024-11-15 14:46 UTC, lidiazuin requested changes
Thanks Natalia! I have added a few suggestions

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +Spring Data Neo4j (SDN) up to version 5.3.x uses Neo4j-OGM under the covers. It’s like Spring Data JPA, where JPA/Hibernate is the underlay. Most of the power of SDN actually comes from Neo4j-OGM. St
```suggestion
Spring Data Neo4j (SDN) up to version 5.3.x uses Neo4j-OGM under the covers. 
It’s like Spring Data JPA, where JPA/Hibernate is the underlay.

Most of the power of SDN actually comes from Neo4j-OGM.
However, starting with Spring Data Neo4j 6.x (Spring Boot 2.4), Neo4j-OGM is not needed anymore. 

Please note that, intentionally, Neo4j-OGM 4+ does not work as a drop-in replacement for Spring Data 5.x.
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +
For some reason there is too little space between the two answers. Maybe this should help.

```suggestion


```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +All concrete classes generate a label, abstract classes and interfaces not. If any kind of class or interface gets annotated with @NodeEntity or @NodeEntity(label="customLabel") it will generate a la
```suggestion
All concrete classes generate a label, but abstract classes and interfaces not. 
If any kind of class or interface gets annotated with `@NodeEntity` or `@NodeEntity(label="customLabel")`, it will generate a label. 
Any class annotated with `@Transient` will not generate a label.
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +Consult the version table to determine which version of Neo4j-OGM to use with a particular version of Neo4j and related technologies.
```suggestion
Check the table to determine which version of Neo4j-OGM to use with a particular version of Neo4j and related technologies:
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +^2^ __These versions only support connections via Bolt.__ +
```suggestion
^2^ __Only supports connections via Bolt.__ +
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +^3^ __These versions are no longer actively developed.__ +
```suggestion
^3^ __No longer actively developed.__ +
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +^4^ __These versions are no longer actively developed or supported.__ +
```suggestion
^4^ __No longer actively developed or supported.__ +
```

2024-11-15 14:46 UTC, lidiazuin commented on modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
> +^6^ __Technical working but not officially supported__ +
```suggestion
^6^ __Technically working, but not officially supported__ +
```

2024-11-15 14:51 UTC, NataliaIvakina commented
hey Lidia! Feel free to do whatever you want. I just wanted to fix links because content was not rendered

2024-11-15 14:54 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-431.surge.sh

Updated pages:
- [Neo4j - OGM Object Graph Mapper](https://neo4j-docs-getting-started-431.surge.sh/getting-started/languages-guides/java/neo4j-ogm)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-11-18 10:44 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-431.surge.sh

Updated pages:
- [Neo4j - OGM Object Graph Mapper](https://neo4j-docs-getting-started-431.surge.sh/getting-started/languages-guides/java/neo4j-ogm)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-11-18 14:24 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-431.surge.sh

Updated pages:
- [Neo4j - OGM Object Graph Mapper](https://neo4j-docs-getting-started-431.surge.sh/getting-started/languages-guides/java/neo4j-ogm)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-11-18 15:43 UTC, lidiazuin approved these changes

2024-11-19 07:27 UTC, merged