New data modeling tutorial
neo4j/docs-getting-started pull request #437
Opened 2024-11-29 14:32 UTC by lidiazuin

2024-11-29 14:33 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-437.surge.sh

New pages:
- [Tutorial: Create a graph data model](https://neo4j-docs-getting-started-437.surge.sh/getting-started/data-modeling/tutorial-data-modeling)

Updated pages:
- [Model your data for Neo4j](https://neo4j-docs-getting-started-437.surge.sh/getting-started/data-modeling)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-12-11 13:00 UTC, AlexicaWright reviewed
I left a lot of comments, that's why it took me so long to review. I hope they are useful!

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +In the example, the use case "What role did a person play in a movie?" could be asked with the help of the property `roles` in the `ACTED_IN` relationship:
```suggestion
The example question "What role did a person play in a movie?" can be asked with the help of the property `roles` in the `ACTED_IN` relationship:
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Note that the information about roles needs to be added to the graph before being retrieved:
```suggestion
You can use this Cypher statement to add information about roles to the `ACTED_IN`relationship:
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This way, you can work with other use cases, such as:
```suggestion
This way, you can answer more questions, such as:
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +To answer these questions, you need information about users and their ratings in your graph, which means a change in your data model.
This would be a good spot to add something about users also being persons and the various ways we can deal with this in the data model.

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +You can start first by adding the users to your graph:
```suggestion
You can start by adding the users to your graph:
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +For example, if you want to test the use case "What people acted in a movie?", you can execute the following query:
```suggestion
For example, if you want to test your model with the question "What people acted in a movie?", you can run the following query:
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +As you go through the use cases, you may think of more data that you want to add to the graph to round out the testing.
```suggestion
As you go through your question, you may think of more data to add to the graph to round out the testing.
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Additionally, make sure that the Cypher code used to test the use cases is correct.
```suggestion
Additionally, make sure that the Cypher statements used to test the use cases are correct.
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +At this point, you will also start considering scalability of your graph and how performant it would be if you write the same queries in a graph with millions of nodes and relationships.
```suggestion
At this point, you can also start considering the scalability of your graph and how performant it would be if you write the same queries in a graph with millions of nodes and relationships.
```

2024-12-11 13:00 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This tutorial is designed to help you understand how data modeling works through an example case.
```suggestion
This tutorial is designed to help you understand how to model your data based on what you intend to use it for.
```

2024-12-12 10:45 UTC, lidiazuin reviewed
Thanks for your thorough review!

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This tutorial is designed to help you understand how data modeling works through an example case.
Not really what you intend to use it for, because it uses a specific use case as an example, and not a general one, one size fits all, sort of.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This helps you to have a better idea of what the application will be, which people and systems will use it, and thus which domain you will work with.
This is what is written in the GraphAcademy course https://graphacademy.neo4j.com/courses/modeling-fundamentals/1-getting-started/2-the-domain/

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +It is in the connections (relationships) between these entities that you find interesting information about your domain.
Also taken from GA, but I suppose this sentence can be tweaked to something like 

```suggestion
It is in the connections (relationships) between these entities that you find insights about your domain.
```

Or remove it.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +With this information, you can better define how the application will behave at runtime.
This is recommendation from the GA course too.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +* What users gave a movie a rating of 5?
No, but in the testing phase, described more ahead, as you realize there are remaining use cases to be answered.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +
I will add an additional step here to create an instance in the user's preferred deployment.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +
Yes, but this is intended, for when you test the model you realize that you missed something.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +However, in order to practice data modeling, it is recommended that you add the data manually using Cypher or link:{docs-home}/data-importer/modeling[Data Importer].
Yeah, better to remove it. Thanks for catching it!

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +== Define entities
It's how it is called in the GA course, and I think it means more like double checking if what you set as a node/relationship before would still work as that or as a property, for example, at this stage.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Node properties are used to uniquely identify a node, answer specific details of the use cases for the application, and to return data.
When I need to know the release date of a movie, and query the property m.release, for example.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +.Return data from the query.
But you query the property to get the data from the property value, no?

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +To get started, thinking of relationships from the perspective that “connections are verbs” works well, but there are other important considerations that you will learn as you advance with your model
I think it sounds weird without the 'will'.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Now, consider a hypothetical scenario in which you decided to have the actors as separate nodes rather than referring to them using the `name` property in `Person` nodes:
The actors are Person nodes and their names/differentiation are found in the property 'name'. When created, they were configured like this:

CREATE (TomH:Person {name:'Tom Hanks'})
CREATE (MegR:Person {name:'Meg Ryan'})

The example here assumes that each actor is a single different role, and so created like this:

CREATE (t:TomH {name:'Tom Hanks'})
CREATE (m:MegR {name:'Meg Ryan'})

But the image is misleading, the node label should be like TomH instead of Tom Hanks, for example. I need to fix that.

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +* What users gave a movie a rating of 5?
```suggestion
* Which users gave a movie a rating of 5?
```

2024-12-12 10:45 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +A query written incorrectly could lead to the assumption that the data model has failed, for example.
Yes, or maybe, for instance, I want to find a user and I forget they are a User node rather than a Person node, so when I query for them using the Person node, then I might think that they don't exist.

2024-12-12 16:21 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +* How many [.underline]#users# rated a [.underline]#movie#?
True, but then we would need to separate actors and directors as different kinds of nodes than Person or add user information in Person nodes. I added a note more below about that. Maybe readers don't pay so much attention to that if we have some explanation further into the tutorial?

2024-12-16 17:42 UTC, AlexicaWright reviewed
A few more comments.

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This tutorial is designed to help you understand how data modeling works through an example case.
No but the idea is general, that you model the data based on what you intend to use it for. In this case we want to use the example data to answer some questions and model it based on those. Do you see what I mean?

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This helps you to have a better idea of what the application will be, which people and systems will use it, and thus which domain you will work with.
Yes, but I'm not sure it is very helpful. But I'll leave that up to you to decide.

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +It is in the connections (relationships) between these entities that you find interesting information about your domain.
That's better, I think.

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +With this information, you can better define how the application will behave at runtime.
Maybe we should try to differentiate this one a little? If we don't give any further explanation to this, I think it is better to omit altogether.

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Node properties are used to uniquely identify a node, answer specific details of the use cases for the application, and to return data.
The query returns the data, not the property. Maybe this can be rephrased to make that a little clearer?

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Now, consider a hypothetical scenario in which you decided to have the actors as separate nodes rather than referring to them using the `name` property in `Person` nodes:
I see what you mean, but the image is not really doing us any favors here. It would look very similar with the Person label.
What you mean is that the actor nodes do not have a Person label? Even with the label to unify the Person nodes, the movie node will still be a super node.

2024-12-16 17:42 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +A query written incorrectly could lead to the assumption that the data model has failed, for example.
I see! I think we should have an example to clarify that.

2024-12-17 09:21 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This tutorial is designed to help you understand how data modeling works through an example case.
yeah, but I don't know if I agree to put it like this here. maybe a middle term could be like

```suggestion
This tutorial is designed to help you understand how to model your data based on what you intend to use it for, using an example case.
```

2024-12-17 09:21 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +With this information, you can better define how the application will behave at runtime.
But I think it's good advice, so you can understand what kind of data you need to add to the graph in order to make it functional for the use cases. I can tweak the sentences a bit, maybe something like:

```suggestion
You can make a *list of questions* to help you identify the use cases of your application.
This way, you can better define what you need from it, and what data needs to be added to the graph.
```

2024-12-17 09:21 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Now, consider a hypothetical scenario in which you decided to have the actors as separate nodes rather than referring to them using the `name` property in `Person` nodes:
I just gave it a second thought and I think this topic is too complex to be addressed here. Alternatively, we could mention the case of super nodes and link to this developer blog article instead -- https://medium.com/neo4j/graph-modeling-all-about-super-nodes-d6ad7e11015b . What do you think?

2025-01-14 09:14 UTC, AlexicaWright commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +With this information, you can better define how the application will behave at runtime.
Or maybe ".., and what data must be included in the graph". At this point, there is no data in the graph.

2025-01-14 11:13 UTC, highton-g commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +You will use the xref:appendix/example-data.adoc[Movies example dataset] as the main resource.
Duplicating what is stated in line 15 below

2025-01-14 13:44 UTC, highton-g approved these changes

2025-01-22 12:26 UTC, martinohanlon reviewed
I think the process is broadly correct. I have added some specific comments and suggestions that I noted.

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +While you can create a property called `name` for both `Person` and `Movie` nodes, it is advisable to use different terms to provide unique identifiers.
Is this true? I dont see why it would be important to have different unique property name for different node labels.

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +While you can create a property called `name` for both `Person` and `Movie` nodes, it is advisable to use different terms to provide unique identifiers.
I think its more important to have property names which reflect the field.

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
This cypher wouldnt run independently (i.e. without being used at the end of the previous Cypher). The variables `TomH` and `Apollo13` arent defined.

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +With the domain defined, you need to identify what the use case is for your application.
```suggestion
With the domain defined, you need to identify your application use cases.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +In this tutorial, you will use the xref:appendix/example-data.adoc[Movies example dataset], which means your domain includes movies, people who acted or directed movies, and users who rated movies.
```suggestion
In this tutorial, you will use the xref:appendix/example-data.adoc[Movies example dataset], the domain includes movies, people who acted or directed movies, and users who rated movies. 
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +You can make a *list of questions* to help you identify the use cases of your application.
```suggestion
You can make a *list of questions* to help you identify the application use cases.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +This way, you can better define what you need from it, and what data must be included in the graph.
```suggestion
The questions will help you define what you need from the application, and what data must be included in the graph.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +For this tutorial, consider these the questions that you want answered by your application:
```suggestion
For this tutorial, your application should be able to answer these questions:
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +
Can you include a definition of what an instance model is (in the same way you do for a domain model?)

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Creating an instance model in the previous step helps you preview how you may define the data as nodes, relationships, and properties.
```suggestion
An instance model helps you preview how the data will be stored as nodes, relationships, and properties.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +The dominant nouns in your application use case are represented as nodes in your model and are used as *node labels*.
```suggestion
The dominant nouns in your application use case are represented as nodes in your model and can be used as *node labels*.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +When you query the database, however, you don't need to specify the direction, as long as the direction is inferred by the order of the pattern in a query.
Minor point, but Im not sure this is important for data modelling. It may just add confusion.

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +As you go through the use cases, you may think of more data to be added to the graph in order to round out the testing.
```suggestion
As you go through the use cases, you may think of more data to be added to the graph in order to complete the testing.
```

2025-01-22 12:26 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +For example, if you want want to find a user, but you forgot that their data is stored as a `User` node rather than a `Person` node, when you query for them using the `Person` node, you won't get any
```suggestion
For example, using an incorrect node label in a test may lead you to believe that the data doesn't exist in the graph.
```

2025-01-23 13:01 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
Well then all other previous code examples using the variables TomH etc, will need to be updated too, right?

2025-01-23 14:16 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
I think its just this one.

2025-01-23 14:28 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
I updated it. Is it correct now or does it still need the MERGE lines like you suggested?

2025-01-23 14:48 UTC, martinohanlon commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
Looks good to me 😄

2025-01-23 14:53 UTC, lidiazuin commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +MATCH (TomH)-[r:ACTED_IN]->(Apollo13)
Awesome, so all your suggestions were already applied in case you want to take a last look 😁

2025-01-23 14:57 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-437.surge.sh

Updated pages:
- [Tutorial: Create a graph data model](https://neo4j-docs-getting-started-437.surge.sh/getting-started/data-modeling/tutorial-data-modeling)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-01-24 14:10 UTC, nmervaillie requested changes
This tutorial is great and provides a lot of value for new graph users. It captures well the essence of data modeling.
The only issue I see is the unique identifiers section.
Left a few comments on what I think could be elaborated a bit more IMO.

2025-01-24 14:10 UTC, nmervaillie commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +Relationship types need to be intuitive and not confused with node labels.
Relationship types need to be specific too.
I thing I often notice when reviewing data models is vague naming such as `HAS`, `RELATED`, `CONNECTED_TO`... As a consequence, the queries are not very expressive. This might cause performance problems as well for dense nodes: Neo4j optimizes queries based on relationship types. If all relationships have the same name, queries must scan many more relationships, slowing down performance. Whereas More specific relationships allow Neo4j to traverse only relevant connections

2025-01-24 14:10 UTC, nmervaillie commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +At this point, you can also start considering the scalability of your graph and how performant it would be if you write the same queries in a graph with millions of nodes and relationships.
how? maybe point the the profiling docs?

2025-01-31 12:08 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-437.surge.sh

Updated pages:
- [Tutorial: Create a graph data model](https://neo4j-docs-getting-started-437.surge.sh/getting-started/data-modeling/tutorial-data-modeling)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2025-02-03 11:38 UTC, nmervaillie approved these changes
Looks good! 
Just one minor suggestion to emphasize the recommendation about unique constraints, but I'm leaving it up to you

2025-02-03 11:38 UTC, nmervaillie commented on modules/ROOT/pages/data-modeling/tutorial-data-modeling.adoc
> +You can enforce unique identifiers by using uniqueness constrains.
suggestion: replace this with "It is strongly suggested that you enforce..."

2025-02-05 11:00 UTC, merged